language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: PMRxqrl3eI5xJXXDrNoZcjVPJ/n9swsOf4lQDAOWoaZEhVEWHITcUxZVhwRFIkaXuB/sZVPvTwvLJBx4AHlqNgQ4QAySaaV5OdxIaKGIqG+cRqhf17xUlnx3T6BQfIZbBbqHkIE7Hf2OC1bqNXxlwRszcJiudpY8eZPYc4Sx+Oj04hXjugl7x3umBZ97VPO0ZsfbjmAXuXen4sO8fMbRvaobwR1qcOxMLAXE2wGO40WIFba8EchcXM0qbKptyhQij/U4P78OmApxLbiv0tAzpdQPAJAephRUPnxpjGwdsm0cJ1ip2PPmyToUl5IjtLQ7sS1KrNRr3pCrJYl5dQK0CLIRuhrCdaGFmbs/Ee+QrdyCFS+F2MDSZpLu9456yZQoELXgtumw6VJ4XByE5AFAe6Ngv6pA6n+9nQIDTnoWkJB2GWQIAViGJ7tTrwa+RVts+n2wsjGObFUcMqt803b6UzT1UQv97nt9GVVPWzYFPfEmxUTPsEPaT6/p05ebg53zhvGOFxSsZ1txapnlmG5C9ZMgD3+yfZCFj+45b/T8u/i2cK01PAP07LAKn3Ue0RpfK08+OboxaYQgd3q1r2Z64VjYE32j/fA+ZBpZ4g9uMKAgD13OH9gZBXby8JeuXHxCVf5b1LCpSxZHUkN90/PkcDWgmjA2s4xH+HXwRqQb6T0=
  app: whispering-shore-83117
  on:
    repo: Kinla/travisHeroku2
env:
  global:
    secure: EiMrg3X7S5xj3R/RxqP9cf9Rhgzh30kYS7nzUlkuSjqEkvVW7i7yMTehT9Y6OysDqVDzBaTsnfmHYrssBAwoN2PabEfA5wiy3h/Js2ldjI3WHaf6Txw3w1Wr2Y9Do8mRQPgObzv1cqctxZhrUSYjyeZ1vBsRNkeJ4Y3ubvkm1Pa3Hca69beyKvxERuvfyVcccZEX/MzSK2d2lsVwLKI4JeeBM6IckwBuER8DC6GeLgguEdJ9fqBvdHCb1/nv2Ie3/euUQZnT7biJcl5anb7Rhf54tjfL/j54NnTUMmVkQ8SznGL40f3czxCQHPLmlrizH3ANpBKeV4ik0VB8Ac/+HzoStTyoMIEEMyhNuS1KYtMaws0qCBhcUdCFTf1sIntCMGUmJ+q+ygkRyW6ABxbLJnsJTMEbVJNXUputfOqZNiXLA3ukhmorROrtIxHZtWotpVdgIDGik9vixLBwI7ux75rNjQDjeYgrMalls4ce8U5+fAG2RePu8yZ0i6st9InNbYCugMwFlF43d9htNvvviYmIwuW+Iq8TYnt/YFJPDnsIY0wCbgy2uaK37/O24HD5iMBhtLnJeoocH1ghT2Ib5gxLzMkG71uAFf4OoqwLGGrf07n03+OhEvng4X9GNrQyI/1+WDyjvISuQmUlFkrmvlGNC4R94RfMYhNdRYhU9uk=
