language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Fb69N2zmBx0oAmIiSY5jA69uI7I9wvuDCJ4anAF7tiSOM7ghX8a8RaOKMS8uG4D66qOxxjFejVmH7yYXJF/9alB2omL1HMeof5XcOwN8GKBQxpK7QLqjBwQ4KTJ94k4iZCxH/PZthykW2hlh+yD1UXsFb1o9swAbd1U04y4l3V/un6BaHh14F9dqAjKXdyg4hczA9XgbEYZOe9pXYD76oReCRcFMa3d+4JItzdlUMVeWtGneAfr6kbytK9ZVXfMlwBsFTF/guebpQgSS6sC0B5J4EPB27Q94KpH4aDdWbfn8oidFlordD8Vq4rAK6WfrfRNzHYyMtBAN5vd7583s7+TI9Qoz9OTvBdUc39iGSU/Cr9GJiZ1XHSJmcZENU7Pqd/n+K9VTPQGUJDXWhUYOUO0DqejlB4IR5O2UHGrWhlyCStItZVyZjRKuL/ec+2x6+qbiSquXaXnC5ngDN2JuZMiJTnUnXVSv8rkKXYoTIdafUASqzv1I3Kk9QhzaedQ6ZAMKEHitLjDE1mcgkovZ2cMTYeCrAtqWC2wfcBnAMc+yD3IpH5p4kWYrwG3wIDhCahwaBWeMZQzuPmQq5l97FkRcNTEvecjnATw/p8buIdH/n4/7zJ+dNkFSjJRI+xhYmzi+cH1oCprDU+es7urWPjXbtrz+IWwsQIsmd68Gb9o=
  app: whispering-shore-83117
  on:
    repo: Kinla/travisHeroku2