language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: dq3ZuDYwDo/tngf/teqElu3CFzbQiAyl2hOkM4jVIZwyFhFGMg7rkm01TwycBbOhZaKiL3IRxLofBmhUjOFdt7Wc+J2KqriPzEuGMt8+J+H1OEfERfJvM+L7DqXAmAwvOpoLnBpTfPXm3n8MHb6ramjRnHKlmRTkUhdYesah8ZDNGHKCFQ/rgmEJ1QWMtNDkP6W5fcMLOP/+m1ONNsi9GLnldzXIEw9cFlKVklAG0ZOQA8qksacJAbsnt7weofcfUP4SbZs+18M11o/oetiO5waehgZBjGvrZlv1THbEs6UdrMvnttzVodslPxLPkd7QaEZau4GTLinmTPljzSdzthzVx2Zr/Jxt7ZFHdMmL7qm0L2A81rdJF6QBLiB70+yCcFfaXL1AcrhZVcSb6mRtq/DtZ1LW/oJgHyYHeIyrXmHGdkoJuPTS2wmU08A4GoO9JtOjAVIVHuRd2e9zMbUDucqeCZaJqcMEY0XICduPh6WoR3fE7P7IZAPOMihQ/RS/B+zmRtF7JX7ETvL7yPymXhVMY/EomlxUimBVnAiQ+B3DTvB8QZeifDc7C62zdCFN3lCJOjxgeCO244UEy+wu00+W3ntC4YK5ghDYY91XWjk1H1YvaDOukXZXPe7FPi3zcQtS3tcQInYExTjWOxXHevpshcd/dnoF+eBbeKVaFc4=
  app: whispering-shore-83117
  on:
    repo: Kinla/travisHeroku2
